kak issue
csookim/qibo_transpiler_cskim pull request #20
Opened 2024-07-15 06:26 UTC by csookim

From the issue #19.

When using Identity and CNOT matrices, the matrix reassembled after the KAK decomposition is different from the original matrix. 

Is it not appropriate to test the KAK decomposition with CNOT and Identity matrices?

2024-07-16 03:47 UTC, marekgluza requested changes
I'm guessing it's WIP but looks good already, thanks! :)

2024-07-16 03:47 UTC, marekgluza commented on src/qibo/transpiler/blocks.py
> +    def unitary(self):
```suggestion
    def _unitary(self):
```

I think the qiboteam usually prefers to denote with the underscore helper functions

2024-07-16 03:47 UTC, marekgluza commented on src/qibo/transpiler/blocks.py
> +        return circuit.unitary()
maybe storing the self.circuit could be useful too?

2024-07-16 03:47 UTC, marekgluza commented on src/qibo/transpiler/blocks.py
> +    # Make a Circuit object and obtain the unitary by running the circuit
```suggestion
```
I guess it's WIP but in final version contain descriptions to mostly the doc string below

'running the circuit' sounds like Circuit.execute - I'd say by casting the circuit into the corresponding unitary matrix

2024-07-16 03:47 UTC, marekgluza commented on src/qibo/transpiler/blocks.py
> +            raise_error(BlockingError, "The block is not entangled and doesn't require KAK decomposition.")
would then the block stay the same?

Can you ask in the qibo meeting for advice if raising errors is the right approach? Because then the user might need to catch them which might be confusing

2024-07-16 03:47 UTC, marekgluza commented on src/qibo/transpiler/unitary_decompositions.py
> +def orth_decomp_of_unitary(X):
```suggestion
def orthogonal_decomposition_of_unitary(X):
```

2024-07-16 03:47 UTC, marekgluza commented on tests/test_transpiler_blocks_kak.py
> +def test_block_kak(qubits):
this top level approach to testing is good - if blocks calls kak then no need to write the test for kak and then for block just for block. This approach is useful in general when tests are needed from scratch

2024-07-16 03:47 UTC, marekgluza commented on tests/test_transpiler_blocks_kak.py
> +def heisenberg_unitary(k):
can you ask in the qibo zoom: helper function should probably not be in the test file, or?

2024-07-16 03:53 UTC, csookim commented on src/qibo/transpiler/blocks.py
> +            raise_error(BlockingError, "The block is not entangled and doesn't require KAK decomposition.")
Ok. Most of the functions in `blocks.py` handle errors with `raise_error`, and I followed that convention.

2024-07-16 04:06 UTC, csookim commented
I've addressed requests

- [ ] Check if helper functions should not be in the test file
- [ ] Check if raising errors is the right approach.

2024-07-18 02:22 UTC, marekgluza approved these changes
Thank you.

Let's 
- [ ] close this here by merging
- [ ] move the files to the qibo repo
- [ ] complete the work there

2024-07-19 08:00 UTC, merged